version: '3.3'

services:
  db:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: mysql
    image: mysql_db:latest
    restart: always
    env_file: 
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - MYSQL_ROOT_HOST=$MYSQL_ROOT_HOST
      - MYSQL_DATABASE=$MYSQL_DATABASE
    networks:
      - db-tier
    ports:
      - ${PORT}:3306
    volumes:
      - ./startup-scripts:/docker-entrypoint-initdb.d
networks:
  db-tier:
    driver: bridge