version: '3.1'

services: 
  db:
    image: mysql/mysql-server:latest
    ports: 
      - 3306:3306
      
    restart: always
  
    ## Setting Environement Variables
    environment: 
      MYSQL_ROOT_PASSWORD: root1234 # Root Password
      MYSQL_USER: admin             # User
      MYSQL_PASSWORD: admin1234     # User Password
